import streamlit as st
import pandas as pd
import json
import datetime
from io import BytesIO

# ── 1. 頁面配置 ─────────────────────────────────────
st.set_page_config(page_title="SOLIDWIZARD | 計畫書產生器", layout="wide")

# 隱藏預設導覽與自定義樣式
st.markdown("""
    <style>
        [data-testid="stSidebarNav"] {display: none;}
        .main-header { color: #1e3a5f; font-weight: 800; font-size: 2.5rem; margin-bottom: 20px; }
        .report-preview { 
            background: #ffffff; 
            border: 2px solid #e2e8f0; 
            padding: 40px; 
            border-radius: 15px; 
            box-shadow: 0 10px 25px rgba(0,0,0,0.05);
            font-family: 'Inter', sans-serif;
        }
    </style>
""", unsafe_allow_html=True)

# ── 2. 資料庫讀取邏輯 ──────────────────────────────────
def get_db():
    try:
        with open("doc_db.json", "r", encoding="utf-8") as f:
            return json.load(f)
    except:
        return []

# ── 3. 品牌導入邏輯範本 ────────────────────────────────
PLAN_TEMPLATES = {
    "Formlabs": {
        "phases": [
            "環境評估：確認電力(110/220V)、通風系統及後處理空間設定",
            "設備安裝：主機定位、樹脂槽/平台建置及 PreForm 軟體連線",
            "技術訓練：切層設定、支撐架構邏輯及清洗固化後處理操作",
            "驗收測試：標準幾何件列印驗證與精度檢核"
        ],
        "requirements": "需具備 IPA 清洗環境、抗化學手套及穩定網路連線。"
    },
    "Scanology": {
        "phases": [
            "環境評估：掃描場域光線控制、物件固定裝置規劃",
            "設備安裝：感測器校正、高階工作站軟體驅動安裝及掃描儀註冊",
            "技術訓練：標誌點佈置、拼接邏輯、點雲優化及逆向工程導出",
            "驗收測試：標準球桿/量塊精確度對比報告"
        ],
        "requirements": "需搭配高階 GPU 工作站、標誌點耗材及穩定光源條件。"
    }
}

# ── 4. 側邊欄：專案資訊輸入 ──────────────────────────
with st.sidebar:
    st.image("https://formlabs.com/favicon.ico", width=40)
    st.title("計畫書參數設定")
    
    proj_name = st.text_input("專案名稱", "數位化生產導入專案")
    client_name = st.text_input("客戶名稱", "XX 科技有限公司")
    owner = st.text_input("負責專員", "SOLIDWIZARD-User")
    
    st.divider()
    brand = st.radio("選擇導入品牌", ["Formlabs", "Scanology"])
    
    # 動態獲取該品牌的設備清單
    db = get_db()
    brand_devs = sorted(list(set([d['device'] for d in db if d['brand'] == brand])))
    if not brand_devs:
        brand_devs = ["Form 4", "Fuse 1"] if brand == "Formlabs" else ["SIMSCAN30", "KSCANX"]
        
    device = st.selectbox("導入設備型號", brand_devs)
    install_date = st.date_input("預計安裝/驗收日期", datetime.date.today() + datetime.timedelta(days=14))

# ── 5. 主畫面：文件挑選與計畫產生 ──────────────────────
st.markdown(f'<div class="main-header">📝 {brand} 產品導入計畫產生系統</div>', unsafe_allow_html=True)

col_left, col_right = st.columns([1, 1.5])

with col_left:
    st.subheader("📌 挑選計畫附錄 (來自資料庫)")
    # 關聯資料庫文件
    relevant_docs = [d for d in db if d['device'] == device or d['brand'] == brand]
    
    selected_docs = []
    if not relevant_docs:
        st.caption("ℹ️ 資料庫中目前無相關文件，將以標點符號跳過。")
    else:
        for i, doc in enumerate(relevant_docs):
            if st.checkbox(f"[{doc['category']}] {doc['title']}", key=f"d_{i}"):
                selected_docs.append(doc)
    
    st.subheader("🛠️ 額外備註")
    custom_note = st.text_area("針對此客戶的特殊需求備註...", placeholder="例如：需在無塵室安裝...")

# ── 6. 生成計畫書內容 ────────────────────────────────
with col_right:
    st.subheader("📄 計畫書預覽")
    
    temp = PLAN_TEMPLATES[brand]
    
    report_content = f"""# 產品導入計畫書 (Project Implementation Plan)

**專案名稱**：{proj_name}
**客戶名稱**：{client_name}
**負責人員**：{owner}
**編製日期**：{datetime.date.today()}

---

## 一、 計畫目標
針對 **{client_name}** 之需求，規劃導入 **{brand} {device}** 解決方案。透過標準化安裝與教育訓練流程，確保設備發揮最大效能並建立數位化作業流程。

## 二、 導入時程與階段任務
| 階段 | 任務說明 | 預計日期 |
| :--- | :--- | :--- |
| **環境預備** | {temp['phases'][0]} | {install_date - datetime.timedelta(days=7)} |
| **設備交貨** | {temp['phases'][1]} | {install_date} |
| **技術培訓** | {temp['phases'][2]} | {install_date + datetime.timedelta(days=1)} |
| **驗收結案** | {temp['phases'][3]} | {install_date + datetime.timedelta(days=2)} |

## 三、 技術資源與附錄文件
本專案提供以下技術文件作為操作參考：
"""
    for doc in selected_docs:
        report_content += f"- [{doc['title']}]({doc['url']}) - *{doc['category']}*\n"
    
    report_content += f"""
## 四、 環境要求與前置作業
- **硬體需求**：{temp['requirements']}
- **特殊備註**：{custom_note if custom_note else "無特殊要求。"}

## 五、 驗收標準
1. 設備完成基本校正與連線測試。
2. 操作人員掌握基礎工作流（從資料準備至成品產出）。
3. 現場示範首件樣品達成預期精度目標。

---
*Generated by SOLIDWIZARD Implementation Engine*
"""
    
    # 預覽區域
    st.markdown(f'<div class="report-preview">', unsafe_allow_html=True)
    st.markdown(report_content)
    st.markdown('</div>', unsafe_allow_html=True)
    
    # 下載按鈕
    st.download_button(
        label="📥 下載計畫書 (.md 格式)",
        data=report_content,
        file_name=f"{client_name}_導入計畫_{brand}.md",
        mime="text/markdown",
        use_container_width=True
    )

st.divider()
st.caption("提示：產出的計畫書採用 Markdown 格式，可直接貼入 Word、Notion 或傳送至 E-mail 使用。")
